name: Mirror to Gitee
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror code to gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/DjTikas
          dst: gitee/Dr_Tikas
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "api-auto-framework"
          force_update: true
          clone_style: https 
